server:
  port: 9010

spring:
  application:
    name: Hackathon-MeterReading
  kafka:
    properties:
      schema-registry: http://localhost:8084
      specific-avro-reader: true
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: hackathon
      topics: t_local_etat_m_materials
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
logging:
  level:
    root: info
    com.rte_france.plasma.hackathon: debug
    org.apache.kafka: debug
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
