server:
  port: 9002

spring:
  application:
    name: Hackathon-MeterReading
  kafka:
    properties:
      schema-registry: not-used
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      #group-id: hackathon
      topics: topicMeterReading
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
logging:
  level:
    root: info
    com.rte_france.plasma.hackathon: debug
    org.apache.kafka: debug
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
